name: .NET CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ./CyberSecurityChatbot/CyberSecurityChatbot.csproj

    - name: Build
      run: dotnet build ./CyberSecurityChatbot/CyberSecurityChatbot.csproj --no-restore

    - name: Run
      run: dotnet run --project ./CyberSecurityChatbot/CyberSecurityChatbot.csproj
